[tool.poetry]
name = "untrade"
version = "0.1.0"
description = "SDK"
authors = ["Siddharth Jain"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
